# -*- coding: utf-8 -*-
"""KNN CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UyhwD8XOe9c8E5yJkz3wazQxOtdofM8J
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

names=['sepal-length','sepal-width','petal-length','petal-width','Class']
dataset=pd.read_csv("Iris.csv",header=0,names=names)
dataset.head(10)

X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,4].values

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=42)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, Y_train)

Y_pred=classifier.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))